version: '3.9'

services:
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'banking'

  app-banking:
    build: ./
    container_name: 'java-app-banking'
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod